"""add configuration table

Revision ID: 8effd1c19c35
Revises: b8f85128d59a
Create Date: 2020-11-29 11:49:37.965484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8effd1c19c35'
down_revision = 'b8f85128d59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ext', sa.String(length=9), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    # ### end Alembic commands ###
