"""initial

Revision ID: b8f85128d59a
Revises: 
Create Date: 2020-11-29 00:19:32.808037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f85128d59a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('card_struct_no', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('card_no', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('post_no', sa.String(length=255), nullable=True),
    sa.Column('birth', sa.String(length=64), nullable=True),
    sa.Column('work', sa.String(length=64), nullable=True),
    sa.Column('salary', sa.String(length=64), nullable=True),
    sa.Column('married', sa.String(length=20), nullable=True),
    sa.Column('education_level', sa.String(length=20), nullable=True),
    sa.Column('car_brand', sa.String(length=200), nullable=True),
    sa.Column('car_service', sa.String(length=200), nullable=True),
    sa.Column('car_config', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_email'), 'car', ['email'], unique=False)
    op.create_index(op.f('ix_car_tel'), 'car', ['tel'], unique=False)
    op.create_table('gongan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('belong_station', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.String(length=64), nullable=True),
    sa.Column('address_available', sa.String(length=10), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('birth', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('card_no', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('bm1', sa.String(length=4), nullable=True),
    sa.Column('bm2', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gongan_tel'), 'gongan', ['tel'], unique=False)
    op.create_table('jiekuan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('native', sa.String(length=255), nullable=True),
    sa.Column('card_util_date', sa.String(length=255), nullable=True),
    sa.Column('card_no_place', sa.String(length=255), nullable=True),
    sa.Column('card_no_address', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('wechat', sa.String(length=255), nullable=True),
    sa.Column('qq', sa.String(length=255), nullable=True),
    sa.Column('card_no', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=255), nullable=True),
    sa.Column('education_level', sa.String(length=255), nullable=True),
    sa.Column('married', sa.String(length=255), nullable=True),
    sa.Column('sons', sa.String(length=255), nullable=True),
    sa.Column('home_type', sa.String(length=255), nullable=True),
    sa.Column('wife_name', sa.String(length=255), nullable=True),
    sa.Column('wife_card_no', sa.String(length=255), nullable=True),
    sa.Column('wife_company', sa.String(length=255), nullable=True),
    sa.Column('direct_namee', sa.String(length=255), nullable=True),
    sa.Column('direct_relation', sa.String(length=255), nullable=True),
    sa.Column('direct_tel', sa.String(length=255), nullable=True),
    sa.Column('direct_address', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('duty', sa.String(length=255), nullable=True),
    sa.Column('job_start_date', sa.String(length=255), nullable=True),
    sa.Column('job_salary_date', sa.String(length=255), nullable=True),
    sa.Column('month_outcome', sa.String(length=255), nullable=True),
    sa.Column('month_income', sa.String(length=255), nullable=True),
    sa.Column('job_initial_date', sa.String(length=255), nullable=True),
    sa.Column('lend_time', sa.String(length=255), nullable=True),
    sa.Column('company_property', sa.String(length=255), nullable=True),
    sa.Column('birth', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jiekuan_qq'), 'jiekuan', ['qq'], unique=False)
    op.create_index(op.f('ix_jiekuan_tel'), 'jiekuan', ['tel'], unique=False)
    op.create_table('jingdong',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_md5', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('card_no', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jingdong_mail'), 'jingdong', ['mail'], unique=False)
    op.create_index(op.f('ix_jingdong_tel'), 'jingdong', ['tel'], unique=False)
    op.create_table('kfc',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('card_no', sa.String(length=255), nullable=True),
    sa.Column('descriot', sa.String(length=255), nullable=True),
    sa.Column('ctf_tp', sa.String(length=255), nullable=True),
    sa.Column('ctf_id', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=60), nullable=True),
    sa.Column('birthday', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zip', sa.String(length=255), nullable=True),
    sa.Column('dirty', sa.String(length=255), nullable=True),
    sa.Column('district1', sa.String(length=255), nullable=True),
    sa.Column('district2', sa.String(length=255), nullable=True),
    sa.Column('district3', sa.String(length=255), nullable=True),
    sa.Column('district4', sa.String(length=255), nullable=True),
    sa.Column('district5', sa.String(length=255), nullable=True),
    sa.Column('district6', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('duty', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('tel', sa.String(length=255), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nation', sa.String(length=255), nullable=True),
    sa.Column('taste', sa.String(length=255), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('c_tel', sa.String(length=20), nullable=True),
    sa.Column('c_address', sa.String(length=255), nullable=True),
    sa.Column('c_zip', sa.String(length=20), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('origin_id', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kfc_email'), 'kfc', ['email'], unique=False)
    op.create_index(op.f('ix_kfc_tel'), 'kfc', ['tel'], unique=False)
    op.create_table('pingan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('money', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('card_no', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('income', sa.String(length=200), nullable=True),
    sa.Column('married', sa.String(length=64), nullable=True),
    sa.Column('insure_form', sa.String(length=64), nullable=True),
    sa.Column('insure_industy', sa.String(length=64), nullable=True),
    sa.Column('insure_aim', sa.String(length=64), nullable=True),
    sa.Column('fee_util', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pingan_email'), 'pingan', ['email'], unique=False)
    op.create_index(op.f('ix_pingan_tel'), 'pingan', ['tel'], unique=False)
    op.create_table('qiye',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('company_keyword', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qiye_tel'), 'qiye', ['tel'], unique=False)
    op.create_table('qq',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('qq', sa.BigInteger(), nullable=False),
    sa.Column('tel', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qq_qq'), 'qq', ['qq'], unique=False)
    op.create_index(op.f('ix_qq_tel'), 'qq', ['tel'], unique=False)
    op.create_table('shunfeng',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('dist', sa.String(length=255), nullable=True),
    sa.Column('addr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shunfeng_tel'), 'shunfeng', ['tel'], unique=False)
    op.create_table('weibo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('tel', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weibo_tel'), 'weibo', ['tel'], unique=False)
    op.create_index(op.f('ix_weibo_uid'), 'weibo', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weibo_uid'), table_name='weibo')
    op.drop_index(op.f('ix_weibo_tel'), table_name='weibo')
    op.drop_table('weibo')
    op.drop_index(op.f('ix_shunfeng_tel'), table_name='shunfeng')
    op.drop_table('shunfeng')
    op.drop_index(op.f('ix_qq_tel'), table_name='qq')
    op.drop_index(op.f('ix_qq_qq'), table_name='qq')
    op.drop_table('qq')
    op.drop_index(op.f('ix_qiye_tel'), table_name='qiye')
    op.drop_table('qiye')
    op.drop_index(op.f('ix_pingan_tel'), table_name='pingan')
    op.drop_index(op.f('ix_pingan_email'), table_name='pingan')
    op.drop_table('pingan')
    op.drop_index(op.f('ix_kfc_tel'), table_name='kfc')
    op.drop_index(op.f('ix_kfc_email'), table_name='kfc')
    op.drop_table('kfc')
    op.drop_index(op.f('ix_jingdong_tel'), table_name='jingdong')
    op.drop_index(op.f('ix_jingdong_mail'), table_name='jingdong')
    op.drop_table('jingdong')
    op.drop_index(op.f('ix_jiekuan_tel'), table_name='jiekuan')
    op.drop_index(op.f('ix_jiekuan_qq'), table_name='jiekuan')
    op.drop_table('jiekuan')
    op.drop_index(op.f('ix_gongan_tel'), table_name='gongan')
    op.drop_table('gongan')
    op.drop_index(op.f('ix_car_tel'), table_name='car')
    op.drop_index(op.f('ix_car_email'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
